/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estructura;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        grafo = new Grafo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarEstrellas = new javax.swing.JDialog();
        jl_nombre = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jb_agregar = new javax.swing.JButton();
        jb_agregarAristas = new javax.swing.JButton();
        jb_salirEstrellas = new javax.swing.JButton();
        jd_agregarAristas = new javax.swing.JDialog();
        jl_punto1 = new javax.swing.JLabel();
        jl_punto2 = new javax.swing.JLabel();
        jl_flecha = new javax.swing.JLabel();
        jc_puntoA = new javax.swing.JComboBox<>();
        jc_puntoB = new javax.swing.JComboBox<>();
        jb_agregarArista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        jb_salirAristas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cb_POrigen = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_PDestino = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lb_tiempo = new javax.swing.JLabel();
        jb_visualizarGrafo = new javax.swing.JButton();
        jb_verRutasCortas = new javax.swing.JButton();
        jmb_menu = new javax.swing.JMenuBar();
        jm_file = new javax.swing.JMenu();
        jmi_ingresarEstrellas = new javax.swing.JMenuItem();

        jd_agregarEstrellas.setTitle("Ingresar Estrellas");

        jl_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_nombre.setText("Nombre Estrella: ");

        tf_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jb_agregar.setText("Agregar");
        jb_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarActionPerformed(evt);
            }
        });

        jb_agregarAristas.setText("Agregar Aristas");
        jb_agregarAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarAristasActionPerformed(evt);
            }
        });

        jb_salirEstrellas.setText("Salir");
        jb_salirEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirEstrellasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarEstrellasLayout = new javax.swing.GroupLayout(jd_agregarEstrellas.getContentPane());
        jd_agregarEstrellas.getContentPane().setLayout(jd_agregarEstrellasLayout);
        jd_agregarEstrellasLayout.setHorizontalGroup(
            jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarEstrellasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_salirEstrellas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_agregarAristas))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jd_agregarEstrellasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jb_agregar, jb_agregarAristas, jl_nombre, tf_nombre});

        jd_agregarEstrellasLayout.setVerticalGroup(
            jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarEstrellasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nombre))
                .addGap(60, 60, 60)
                .addGroup(jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_agregar)
                    .addComponent(jb_agregarAristas))
                .addGap(37, 37, 37)
                .addComponent(jb_salirEstrellas)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jd_agregarEstrellasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jl_nombre, tf_nombre});

        jl_punto1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_punto1.setText("Punto A");

        jl_punto2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_punto2.setText("Punto B");

        jl_flecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_flecha.setText("--->");

        jb_agregarArista.setText("Agregar Arista");
        jb_agregarArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarAristaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Peso");

        jb_salirAristas.setText("Salir");
        jb_salirAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirAristasActionPerformed(evt);
            }
        });

        jLabel2.setText("Estrellas");

        jLabel3.setText("Estrellas");

        javax.swing.GroupLayout jd_agregarAristasLayout = new javax.swing.GroupLayout(jd_agregarAristas.getContentPane());
        jd_agregarAristas.getContentPane().setLayout(jd_agregarAristasLayout);
        jd_agregarAristasLayout.setHorizontalGroup(
            jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_salirAristas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_agregarArista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                        .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_peso))
                            .addComponent(jc_puntoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jl_punto1)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jl_flecha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jc_puntoB, 0, 90, Short.MAX_VALUE)
                    .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jl_punto2))
                    .addComponent(jLabel3))
                .addGap(75, 75, 75))
        );

        jd_agregarAristasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jc_puntoA, jc_puntoB});

        jd_agregarAristasLayout.setVerticalGroup(
            jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_punto1)
                    .addComponent(jl_punto2)
                    .addComponent(jl_flecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_puntoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_puntoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jb_agregarArista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jb_salirAristas)
                .addGap(19, 19, 19))
        );

        jd_agregarAristasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, tf_peso});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jLabel4.setText("Punto de origen");

        cb_POrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_POrigenActionPerformed(evt);
            }
        });

        jLabel5.setText("Destino");

        jButton1.setText("Encontrar el camino mas corto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jLabel6.setText("Tiempo de llegada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_POrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_PDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_tiempo))
                            .addComponent(jButton2))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_POrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_PDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lb_tiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Ejercicio", jPanel2);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Star Traveler");

        jb_visualizarGrafo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jb_visualizarGrafo.setText("Visualizar Estrellas");
        jb_visualizarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_visualizarGrafoActionPerformed(evt);
            }
        });

        jb_verRutasCortas.setText("Ver Rutas Cortas");
        jb_verRutasCortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_verRutasCortasActionPerformed(evt);
            }
        });

        jm_file.setText("File");

        jmi_ingresarEstrellas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmi_ingresarEstrellas.setText("Ingresar Estrellas");
        jmi_ingresarEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ingresarEstrellasActionPerformed(evt);
            }
        });
        jm_file.add(jmi_ingresarEstrellas);

        jmb_menu.add(jm_file);

        setJMenuBar(jmb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jb_visualizarGrafo)
                .addGap(27, 27, 27)
                .addComponent(jb_verRutasCortas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_visualizarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_verRutasCortas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_ingresarEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ingresarEstrellasActionPerformed
        // TODO add your handling code here:
        jd_agregarEstrellas.setModal(true);
        jd_agregarEstrellas.pack();
        jd_agregarEstrellas.setLocationRelativeTo(this);
        jd_agregarEstrellas.setVisible(true);
    }//GEN-LAST:event_jmi_ingresarEstrellasActionPerformed

    private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
        // TODO add your handling code here:
        try {
            int id = grafo.getVertices().size()+1;
            Estrella estrella = new Estrella(id,tf_nombre.getText());
            grafo.AddVertice(estrella);
            System.out.println(id);
            tf_nombre.setText("");
            JOptionPane.showMessageDialog(null, "Estrella Agregada!");
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jb_agregarActionPerformed

    private void jb_agregarAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarAristasActionPerformed
        // TODO add your handling code here:
        try {
            jc_puntoA.removeAllItems();
            jc_puntoA.removeAllItems();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            DefaultComboBoxModel model2 = new DefaultComboBoxModel();
            for (int i = 0; i < grafo.getVertices().size(); i++) {
                model.addElement((Estrella)grafo.getVertices().get(i).getValor());
                model2.addElement((Estrella)grafo.getVertices().get(i).getValor());
            }
            jc_puntoA.setModel(model);
            jc_puntoB.setModel(model2);
            jd_agregarAristas.setModal(true);
            jd_agregarAristas.pack();
            jd_agregarAristas.setLocationRelativeTo(this);
            jd_agregarAristas.setVisible(true);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jb_agregarAristasActionPerformed

    private void jb_agregarAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarAristaActionPerformed
        // TODO add your handling code here:
        try {
            Estrella puntoA = (Estrella)jc_puntoA.getSelectedItem();
            Estrella puntoB = (Estrella) jc_puntoB.getSelectedItem();
            int peso = Integer.parseInt(tf_peso.getText());
            Arista arista = new Arista(Color.BLACK,puntoA,puntoB,peso);
            grafo.AddArista(arista);
            System.out.println("Arista Agregada: " +arista);
            tf_peso.setText("");
            JOptionPane.showMessageDialog(null, "Arista Agregada");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jb_agregarAristaActionPerformed

    private void jb_visualizarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_visualizarGrafoActionPerformed
        // TODO add your handling code here:
        try {
            Dibujar dibujar = new Dibujar();
            dibujar.dibujarGrafo(grafo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jb_visualizarGrafoActionPerformed

    private void jb_salirAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirAristasActionPerformed
        // TODO add your handling code here:
        jd_agregarAristas.setVisible(false);
    }//GEN-LAST:event_jb_salirAristasActionPerformed

    private void jb_salirEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirEstrellasActionPerformed
        // TODO add your handling code here:
        jd_agregarEstrellas.setVisible(false);
    }//GEN-LAST:event_jb_salirEstrellasActionPerformed

    private void jb_verRutasCortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_verRutasCortasActionPerformed
        // TODO add your handling code here:
        Dibujar db = new Dibujar();
        Grafo mst = grafo.algoritmoPrim(adyacencias, grafo);
        db.dibujarGrafo(mst);
    }//GEN-LAST:event_jb_verRutasCortasActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            modelo.addElement((Estrella)grafo.getVertices().get(i).getValor());
        }
        this.cb_POrigen.setModel(modelo);
    }//GEN-LAST:event_jPanel2ComponentShown

    private void cb_POrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_POrigenActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo=new DefaultComboBoxModel();
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            if ((Estrella)grafo.getVertices().get(i).getValor()!=(Estrella)this.cb_POrigen.getSelectedItem()) {
                modelo.addElement((Estrella)grafo.getVertices().get(i).getValor());
            }
        }
        this.cb_PDestino.setModel(modelo);
    }//GEN-LAST:event_cb_POrigenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Lista camino=Dijkstra((Estrella)this.cb_POrigen.getSelectedItem(),(Estrella)this.cb_PDestino.getSelectedItem(),grafo);
        Arista temporal;
        for (int i = 0; i < camino.size(); i++) {
            for (int j = 0; j < camino.size()-1; j++) {
                if (((Arista)camino.get(j).getValor()).getPeso()<((Arista)camino.get(j+1).getValor()).getPeso()) {
                    temporal=((Arista)camino.get(j).getValor());
                    camino.get(j).setValor(((Arista)camino.get(j+1).getValor()));
                    camino.get(j+1).setValor(temporal);
                }
            }
        }
        int tiempo=0;
        for (int i = 0; i < camino.size(); i++) {
            if (i>2) {
                tiempo+=((Arista)camino.get(i).getValor()).getPeso();
                ((Arista)camino.get(i).getValor()).setColor(Color.blue);
            }else{
                ((Arista)camino.get(i).getValor()).setColor(Color.YELLOW);
            }
        }
        this.lb_tiempo.setText(tiempo+"");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    static Lista Dijkstra(Estrella origen,Estrella destino, Grafo grafo) {
        Lista camino=new Lista();
        
        int[][] matriz = new int[grafo.getVertices().size()][grafo.getVertices().size()];
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[0].length; j++) {
                matriz[i][j] = Integer.MAX_VALUE;
            }
        }
        Pila adyacentes = new Pila();
        Cola adyacentes3 = new Cola();
        Estrella actual = origen;
        for (int i = 0; i < grafo.getVertices().size(); i++) {
            adyacentes = Adyacentes(actual, grafo, adyacentes);
            while (!adyacentes.IsEmpty()) {
                Estrella temporal = (Estrella) adyacentes.Desapilar();
                adyacentes3.queue(temporal);
                int peso = Peso(actual, temporal, grafo, origen);
                if (i > 0) {
                    if (peso < matriz[i - 1][temporal.getId() - 1]) {
                        matriz[i][temporal.getId() - 1] = Peso(actual, temporal, grafo, origen);
                        if (temporal.getId()==destino.getId()) {//----------------->aqui
                            camino=Camino(actual,temporal,grafo,origen);
                        }
                    } else {
                        matriz[i][temporal.getId() - 1] = matriz[i - 1][temporal.getId() - 1];
                    }
                } else {
                    matriz[i][temporal.getId() - 1] = Peso(actual, temporal, grafo, origen);
                    if (temporal.getId()==destino.getId()) {//----------------->aqui
                            camino=Camino(actual,temporal,grafo,origen);
                    }
                }

            }
            if (!adyacentes3.isEmpty()) {
                actual = (Estrella) adyacentes3.Dequeue();
            }

        }
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[0].length; j++) {
                if (i > 0) {
                    if (matriz[i - 1][j] < matriz[i][j]) {
                        matriz[i][j] = matriz[i - 1][j];
                    }
                }
                System.out.print("[" + matriz[i][j] + "]");
            }
            System.out.println("");
        }
          
        return camino;
    }
    static int Peso(Estrella puntoA, Estrella puntoB, Grafo grafo, Estrella origen) {
        int peso = 0, peso2 = 0;
        for (int i = 0; i < grafo.getAristas().size(); i++) {
            if (((Arista) grafo.getAristas().get(i).getValor()).getPuntoA() == puntoA
                    && ((Arista) grafo.getAristas().get(i).getValor()).getPuntoB() == puntoB && ((Arista) grafo.getAristas().get(i).getValor()).getPuntoA() == origen) {
                peso = ((Arista) grafo.getAristas().get(i).getValor()).getPeso();
            } else if ((((Arista) grafo.getAristas().get(i).getValor()).getPuntoA() == puntoA
                    && ((Arista) grafo.getAristas().get(i).getValor()).getPuntoB() == puntoB)) {
                Estrella anterior = origen;
                boolean noEncontrado = true;
                Pila adyacentes = new Pila();
                Cola adyacentes3 = new Cola();
                do {
                    adyacentes = Adyacentes(anterior, grafo, adyacentes);
                    while (!adyacentes.IsEmpty()) {
                        Estrella temporal = (Estrella) adyacentes.Desapilar();
                        adyacentes3.queue(temporal);
                        if (temporal.getId() == puntoA.getId()) {
                            noEncontrado = false;
                            break;
                        }
                    }
                    if (noEncontrado) {
                        if (!adyacentes3.isEmpty()) {
                            anterior = (Estrella) adyacentes3.Dequeue();
                        } else {
                            noEncontrado = false;
                        }
                    }
                } while (noEncontrado);
                for (int j = 0; j < grafo.getAristas().size(); j++) {
                    if (((Arista) grafo.getAristas().get(j).getValor()).getPuntoA() == anterior && ((Arista) grafo.getAristas().get(j).getValor()).getPuntoB() == puntoA) {
                        peso2 += ((Arista) grafo.getAristas().get(j).getValor()).getPeso();
                    }
                }
                Estrella temPuntoA = origen;
                if (anterior.getId() != origen.getId()) {
                    do {
                        noEncontrado = true;
                        adyacentes = new Pila();
                        adyacentes3 = new Cola();

                        do {
                            adyacentes = Adyacentes(temPuntoA, grafo, adyacentes);
                            while (!adyacentes.IsEmpty()) {
                                Estrella temporal = (Estrella) adyacentes.Desapilar();
                                adyacentes3.queue(temporal);
                                if (temporal.getId() == anterior.getId()) {
                                    noEncontrado = false;
                                    break;
                                }
                            }
                            if (noEncontrado) {
                                if (!adyacentes3.isEmpty()) {
                                    temPuntoA = (Estrella) adyacentes3.Dequeue();
                                } else {
                                    noEncontrado = false;
                                }
                            }
                        } while (noEncontrado);
                        for (int j = 0; j < grafo.getAristas().size(); j++) {
                            if (((Arista) grafo.getAristas().get(j).getValor()).getPuntoA() == temPuntoA && ((Arista) grafo.getAristas().get(j).getValor()).getPuntoB() == anterior) {
                                peso2 += ((Arista) grafo.getAristas().get(j).getValor()).getPeso();
                            }
                        }
                        anterior = temPuntoA;
                    } while (temPuntoA.getId() != origen.getId());
                }
                peso = ((Arista) grafo.getAristas().get(i).getValor()).getPeso() + peso2;
            }
        }
        return peso;
    }
    static Lista Camino(Estrella puntoA, Estrella puntoB, Grafo grafo, Estrella origen) {
        Lista aristas=new Lista();
        for (int i = 0; i < grafo.getAristas().size(); i++) {
            if (((Arista) grafo.getAristas().get(i).getValor()).getPuntoA() == puntoA
                    && ((Arista) grafo.getAristas().get(i).getValor()).getPuntoB() == puntoB && ((Arista) grafo.getAristas().get(i).getValor()).getPuntoA() == origen) {
                aristas.insert(new Nodo(null,(Arista)grafo.getAristas().get(i).getValor()));
            } else if ((((Arista) grafo.getAristas().get(i).getValor()).getPuntoA() == puntoA
                    && ((Arista) grafo.getAristas().get(i).getValor()).getPuntoB() == puntoB)) {
                Estrella anterior = origen;
                boolean noEncontrado = true;
                Pila adyacentes = new Pila();
                Cola adyacentes3 = new Cola();
                do {
                    adyacentes = Adyacentes(anterior, grafo, adyacentes);
                    while (!adyacentes.IsEmpty()) {
                        Estrella temporal = (Estrella) adyacentes.Desapilar();
                        adyacentes3.queue(temporal);
                        if (temporal.getId() == puntoA.getId()) {
                            noEncontrado = false;
                            break;
                        }
                    }
                    if (noEncontrado) {
                        if (!adyacentes3.isEmpty()) {
                            anterior = (Estrella) adyacentes3.Dequeue();
                        } else {
                            noEncontrado = false;
                        }
                    }
                } while (noEncontrado);
                for (int j = 0; j < grafo.getAristas().size(); j++) {
                    if (((Arista) grafo.getAristas().get(j).getValor()).getPuntoA() == anterior && ((Arista) grafo.getAristas().get(j).getValor()).getPuntoB() == puntoA) {
                        aristas.insert(new Nodo(null,(Arista)grafo.getAristas().get(j).getValor()));
                    }
                }
                Estrella temPuntoA = origen;
                if (anterior.getId() != origen.getId()) {
                    do {
                        noEncontrado = true;
                        adyacentes = new Pila();
                        adyacentes3 = new Cola();

                        do {
                            adyacentes = Adyacentes(temPuntoA, grafo, adyacentes);
                            while (!adyacentes.IsEmpty()) {
                                Estrella temporal = (Estrella) adyacentes.Desapilar();
                                adyacentes3.queue(temporal);
                                if (temporal.getId() == anterior.getId()) {
                                    noEncontrado = false;
                                    break;
                                }
                            }
                            if (noEncontrado) {
                                if (!adyacentes3.isEmpty()) {
                                    temPuntoA = (Estrella) adyacentes3.Dequeue();
                                } else {
                                    noEncontrado = false;
                                }
                            }
                        } while (noEncontrado);
                        for (int j = 0; j < grafo.getAristas().size(); j++) {
                            if (((Arista) grafo.getAristas().get(j).getValor()).getPuntoA() == temPuntoA && ((Arista) grafo.getAristas().get(j).getValor()).getPuntoB() == anterior) {
                                aristas.insert(new Nodo(null,(Arista)grafo.getAristas().get(j).getValor()));
                            }
                        }
                        anterior = temPuntoA;
                    } while (temPuntoA.getId() != origen.getId());
                }
                aristas.insert(new Nodo(null,(Arista)grafo.getAristas().get(i).getValor()));
            }
        }
        return aristas;
    }
    static Pila Adyacentes(Estrella actual, Grafo grafo, Pila adyacentes) {
        for (int i = 0; i < grafo.getAristas().size(); i++) {
            if (((Arista) grafo.getAristas().get(i).getValor()).getPuntoA().getId() == actual.getId()) {
                adyacentes.Apilar((Estrella) ((Arista) grafo.getAristas().get(i).getValor()).getPuntoB());
            }
            /* if (i == actual.getNumAristas()) {
                break;
            }*/
        }
        adyacentes.ordenar();
        return adyacentes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_PDestino;
    private javax.swing.JComboBox<String> cb_POrigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_agregarArista;
    private javax.swing.JButton jb_agregarAristas;
    private javax.swing.JButton jb_salirAristas;
    private javax.swing.JButton jb_salirEstrellas;
    private javax.swing.JButton jb_verRutasCortas;
    private javax.swing.JButton jb_visualizarGrafo;
    private javax.swing.JComboBox<String> jc_puntoA;
    private javax.swing.JComboBox<String> jc_puntoB;
    private javax.swing.JDialog jd_agregarAristas;
    private javax.swing.JDialog jd_agregarEstrellas;
    private javax.swing.JLabel jl_flecha;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_punto1;
    private javax.swing.JLabel jl_punto2;
    private javax.swing.JMenu jm_file;
    private javax.swing.JMenuBar jmb_menu;
    private javax.swing.JMenuItem jmi_ingresarEstrellas;
    private javax.swing.JLabel lb_tiempo;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_peso;
    // End of variables declaration//GEN-END:variables
    Grafo grafo;
    int adyacencias[][]= {{0,10,15,31,0},
                             {10,0,43,7,0},
                             {15,43,15,0,20},
                             {31,7,0,0,60},
                             {0,0,20,60,0}};
}


