/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estructura;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        grafo = new Grafo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarEstrellas = new javax.swing.JDialog();
        jl_nombre = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jb_agregar = new javax.swing.JButton();
        jb_agregarAristas = new javax.swing.JButton();
        jb_salirEstrellas = new javax.swing.JButton();
        jd_agregarAristas = new javax.swing.JDialog();
        jl_punto1 = new javax.swing.JLabel();
        jl_punto2 = new javax.swing.JLabel();
        jl_flecha = new javax.swing.JLabel();
        jc_puntoA = new javax.swing.JComboBox<>();
        jc_puntoB = new javax.swing.JComboBox<>();
        jb_agregarArista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        jb_salirAristas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_visualizarGrafo = new javax.swing.JButton();
        jb_verRutasCortas = new javax.swing.JButton();
        jmb_menu = new javax.swing.JMenuBar();
        jm_file = new javax.swing.JMenu();
        jmi_ingresarEstrellas = new javax.swing.JMenuItem();

        jd_agregarEstrellas.setTitle("Ingresar Estrellas");

        jl_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_nombre.setText("Nombre Estrella: ");

        tf_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jb_agregar.setText("Agregar");
        jb_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarActionPerformed(evt);
            }
        });

        jb_agregarAristas.setText("Agregar Aristas");
        jb_agregarAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarAristasActionPerformed(evt);
            }
        });

        jb_salirEstrellas.setText("Salir");
        jb_salirEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirEstrellasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarEstrellasLayout = new javax.swing.GroupLayout(jd_agregarEstrellas.getContentPane());
        jd_agregarEstrellas.getContentPane().setLayout(jd_agregarEstrellasLayout);
        jd_agregarEstrellasLayout.setHorizontalGroup(
            jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarEstrellasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_salirEstrellas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_agregarAristas))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jd_agregarEstrellasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jb_agregar, jb_agregarAristas, jl_nombre, tf_nombre});

        jd_agregarEstrellasLayout.setVerticalGroup(
            jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarEstrellasLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nombre))
                .addGap(60, 60, 60)
                .addGroup(jd_agregarEstrellasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_agregar)
                    .addComponent(jb_agregarAristas))
                .addGap(37, 37, 37)
                .addComponent(jb_salirEstrellas)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jd_agregarEstrellasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jl_nombre, tf_nombre});

        jl_punto1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_punto1.setText("Punto A");

        jl_punto2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_punto2.setText("Punto B");

        jl_flecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_flecha.setText("--->");

        jb_agregarArista.setText("Agregar Arista");
        jb_agregarArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarAristaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Peso");

        jb_salirAristas.setText("Salir");
        jb_salirAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirAristasActionPerformed(evt);
            }
        });

        jLabel2.setText("Estrellas");

        jLabel3.setText("Estrellas");

        javax.swing.GroupLayout jd_agregarAristasLayout = new javax.swing.GroupLayout(jd_agregarAristas.getContentPane());
        jd_agregarAristas.getContentPane().setLayout(jd_agregarAristasLayout);
        jd_agregarAristasLayout.setHorizontalGroup(
            jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_salirAristas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_agregarArista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                        .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_peso))
                            .addComponent(jc_puntoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jl_punto1)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jl_flecha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jc_puntoB, 0, 90, Short.MAX_VALUE)
                    .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jl_punto2))
                    .addComponent(jLabel3))
                .addGap(75, 75, 75))
        );

        jd_agregarAristasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jc_puntoA, jc_puntoB});

        jd_agregarAristasLayout.setVerticalGroup(
            jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarAristasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_punto1)
                    .addComponent(jl_punto2)
                    .addComponent(jl_flecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_puntoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_puntoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_agregarAristasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jb_agregarArista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jb_salirAristas)
                .addGap(19, 19, 19))
        );

        jd_agregarAristasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, tf_peso});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Star Traveler");

        jb_visualizarGrafo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jb_visualizarGrafo.setText("Visualizar Estrellas");
        jb_visualizarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_visualizarGrafoActionPerformed(evt);
            }
        });

        jb_verRutasCortas.setText("Ver Rutas Cortas");
        jb_verRutasCortas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_verRutasCortasActionPerformed(evt);
            }
        });

        jm_file.setText("File");

        jmi_ingresarEstrellas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmi_ingresarEstrellas.setText("Ingresar Estrellas");
        jmi_ingresarEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ingresarEstrellasActionPerformed(evt);
            }
        });
        jm_file.add(jmi_ingresarEstrellas);

        jmb_menu.add(jm_file);

        setJMenuBar(jmb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jb_visualizarGrafo)
                .addGap(27, 27, 27)
                .addComponent(jb_verRutasCortas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_visualizarGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_verRutasCortas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_ingresarEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ingresarEstrellasActionPerformed
        // TODO add your handling code here:
        jd_agregarEstrellas.setModal(true);
        jd_agregarEstrellas.pack();
        jd_agregarEstrellas.setLocationRelativeTo(this);
        jd_agregarEstrellas.setVisible(true);
    }//GEN-LAST:event_jmi_ingresarEstrellasActionPerformed

    private void jb_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarActionPerformed
        // TODO add your handling code here:
        try {
            int id = grafo.getVertices().size()+1;
            Estrella estrella = new Estrella(id,tf_nombre.getText());
            grafo.AddVertice(estrella);
            System.out.println(id);
            tf_nombre.setText("");
            JOptionPane.showMessageDialog(null, "Estrella Agregada!");
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jb_agregarActionPerformed

    private void jb_agregarAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarAristasActionPerformed
        // TODO add your handling code here:
        try {
            jc_puntoA.removeAllItems();
            jc_puntoA.removeAllItems();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            DefaultComboBoxModel model2 = new DefaultComboBoxModel();
            for (int i = 0; i < grafo.getVertices().size(); i++) {
                model.addElement((Estrella)grafo.getVertices().get(i).getValor());
                model2.addElement((Estrella)grafo.getVertices().get(i).getValor());
            }
            jc_puntoA.setModel(model);
            jc_puntoB.setModel(model2);
            jd_agregarAristas.setModal(true);
            jd_agregarAristas.pack();
            jd_agregarAristas.setLocationRelativeTo(this);
            jd_agregarAristas.setVisible(true);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jb_agregarAristasActionPerformed

    private void jb_agregarAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarAristaActionPerformed
        // TODO add your handling code here:
        try {
            Estrella puntoA = (Estrella)jc_puntoA.getSelectedItem();
            Estrella puntoB = (Estrella) jc_puntoB.getSelectedItem();
            int peso = Integer.parseInt(tf_peso.getText());
            Arista arista = new Arista(Color.BLACK,puntoA,puntoB,peso);
            grafo.AddArista(arista);
            System.out.println("Arista Agregada: " +arista);
            tf_peso.setText("");
            JOptionPane.showMessageDialog(null, "Arista Agregada");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jb_agregarAristaActionPerformed

    private void jb_visualizarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_visualizarGrafoActionPerformed
        // TODO add your handling code here:
        try {
            Dibujar dibujar = new Dibujar();
            dibujar.dibujarGrafo(grafo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jb_visualizarGrafoActionPerformed

    private void jb_salirAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirAristasActionPerformed
        // TODO add your handling code here:
        jd_agregarAristas.setVisible(false);
    }//GEN-LAST:event_jb_salirAristasActionPerformed

    private void jb_salirEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirEstrellasActionPerformed
        // TODO add your handling code here:
        jd_agregarEstrellas.setVisible(false);
    }//GEN-LAST:event_jb_salirEstrellasActionPerformed

    private void jb_verRutasCortasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_verRutasCortasActionPerformed
        // TODO add your handling code here:
        Dibujar db = new Dibujar();
        Grafo mst = grafo.algoritmoPrim(adyacencias, grafo);
        db.dibujarGrafo(mst);
    }//GEN-LAST:event_jb_verRutasCortasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_agregarArista;
    private javax.swing.JButton jb_agregarAristas;
    private javax.swing.JButton jb_salirAristas;
    private javax.swing.JButton jb_salirEstrellas;
    private javax.swing.JButton jb_verRutasCortas;
    private javax.swing.JButton jb_visualizarGrafo;
    private javax.swing.JComboBox<String> jc_puntoA;
    private javax.swing.JComboBox<String> jc_puntoB;
    private javax.swing.JDialog jd_agregarAristas;
    private javax.swing.JDialog jd_agregarEstrellas;
    private javax.swing.JLabel jl_flecha;
    private javax.swing.JLabel jl_nombre;
    private javax.swing.JLabel jl_punto1;
    private javax.swing.JLabel jl_punto2;
    private javax.swing.JMenu jm_file;
    private javax.swing.JMenuBar jmb_menu;
    private javax.swing.JMenuItem jmi_ingresarEstrellas;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_peso;
    // End of variables declaration//GEN-END:variables
    Grafo grafo;
    int adyacencias[][]= {{0,10,15,31,0},
                             {10,0,43,7,0},
                             {15,43,15,0,20},
                             {31,7,0,0,60},
                             {0,0,20,60,0}};
}


